### ISSUE TITLE
Fresh install, missing /vendor/autoload.php

### ISSUE THREAD

**Issue by HappinessPK** [pbbg-io/mccodesfree#1]
I ran a fresh install to check it out, but I can not use the installer as an error pops up.

It seems to be looking for /vendor/autoload.php but with the files there is no "vendor" folder at all.

`Warning: require(/home/playkito/public_html/vendor/autoload.php): failed to open stream: No such file or directory in /home/playkito/public_html/global_func.php on line 21

Warning: require(/home/playkito/public_html/vendor/autoload.php): failed to open stream: No such file or directory in /home/playkito/public_html/global_func.php on line 21

Fatal error: require(): Failed opening required '/home/playkito/public_html/vendor/autoload.php' (include_path='.:/opt/alt/php72/usr/share/pear') in /home/playkito/public_html/global_func.php on line 21`

**Comment by 1e4** [comment]
You need to install composer and run composer install to install the vendor/

**Comment by HappinessPK** [comment]
Oh, okey. Thanks.
